version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rule-engine
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/rule-engine?authSource=admin

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  mongo-data:
